Migrate from TravisCI to Github Actions
sofastack/sofa-registry pull request #155
Opened 2021-02-25 06:44 UTC by NickNYU

### Motivation:

- More github native way to run workflows
- Due to the policy change of TravisCI

### Modification:

- Add a github style workflow
- Readme.md: Replace the TravisCI badge with Github's

### Result:

Shown as readme

2021-02-25 07:30 UTC, ujjboy requested changes

2021-02-25 07:30 UTC, ujjboy commented on README.md
> +[![Java CI with Maven](https://github.com/NickNYU/sofa-registry/actions/workflows/maven.yml/badge.svg)](https://github.com/NickNYU/sofa-registry/actions/workflows/maven.yml)
https://github.com/NickNYU/sofa-registry  --> https://github.com/sofastack/sofa-registry

2021-02-25 12:17 UTC, ujjboy requested changes

2021-02-25 12:17 UTC, ujjboy commented on README.md
> +[![Java CI with Maven](https://github.com/sofastack/sofa-registry/actions/workflows/maven.yml/badge.svg)](https://github.com/NickNYU/sofa-registry/actions/workflows/maven.yml)
还有一个地方 NickNYU 没改

2021-03-04 09:40 UTC, NickNYU commented on README.md
> +[![Java CI with Maven](https://github.com/sofastack/sofa-registry/actions/workflows/maven.yml/badge.svg)](https://github.com/NickNYU/sofa-registry/actions/workflows/maven.yml)
尴尬

2021-03-07 12:02 UTC, ujjboy approved these changes

2021-03-25 03:07 UTC, merged